name: build_test

on:
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:

  check-WRF:
    strategy:
      matrix:
        version: [0, 1, 2, 3] # WRF-3.9.1.1, WRF-4.2, WRF-4.3, WRF-4.4.2
        os: [ubuntu-22.04, ubuntu-20.04]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - name: check WRF
        run: autoInstall.sh -d "./" -f 1 -v ${{ matrix.version }} -c 0 -n 2 -s 0
        shell: bash

  check-WRF-chem:
    strategy:
      matrix:
        version: [0, 1, 2, 3] # WRF-3.9.1.1, WRF-4.2, WRF-4.3, WRF-4.4.2
        os: [ubuntu-22.04, ubuntu-20.04]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - name: check WRF-chem
        run: autoInstall.sh -d "./" -f 2 -v ${{ matrix.version }} -c 0 -n 2 -s 0
        shell: bash

  check-WRF-hydro:
    strategy:
      matrix:
        version: [0, 1, 2, 3] # WRF-3.9.1.1, WRF-4.2, WRF-4.3, WRF-4.4.2
        os: [ubuntu-22.04, ubuntu-20.04]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - name: check WRF-hydro
        run: autoInstall.sh -d "./" -f 3 -v ${{ matrix.version }} -c 0 -n 2 -s 0
        shell: bash

  check-WRF-4dvar:
    strategy:
      matrix:
        version: [0, 1, 2, 3] # WRF-3.9.1.1, WRF-4.2, WRF-4.3, WRF-4.4.2
        os: [ubuntu-22.04, ubuntu-20.04]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - name: check WRF-4dvar
        run: autoInstall.sh -d "./" -f 4 -v ${{ matrix.version }} -c 0 -n 2 -s 0
        shell: bash